#!/bin/sh

source ./nativefy.conf

system_el_version=$(electron -v | cut -c2-)
npm_el_version=$(npm list electron | grep electron | cut -d'@' -f2)

[ $electron_version == default ] && build_el_version=$system_el_version || build_el_version=$npm_el_version

echo "Packaging with electron v$build_el_version"

echo "please enter webaddress:"
read webaddress

echo "please enter a name:"
read webapp_display_name

webapp_name=$(echo $webapp_display_name | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
output_desktop_file="$webapp_name.desktop"

# sourced from nativefy.conf
cd $webapps_folder

nativefier -u $user_agent_str -e $build_el_version -n "$webapp_name" $webaddress

cd "$webapp_name-linux*" || echo "duplicates detectet"

startup_wm_class="$(cat resources/app/package.json | jq .name | cut -d"\"" -f2)"
exec_path="$(pwd)/$webapp_name"
icon_path="$(pwd)/resources/app/icon.png"

echo "Exec=$exec_path" >> $output_desktop_file
echo "Name=$webapp_display_name" >> $output_desktop_file
echo "Icon=$icon_path" >> $output_desktop_file
echo "StartupWMClass=$wm_class" >> $output_desktop_file


#cp $output_desktop_file ~/.local/share/applications/$webapp_name.desktop
